networks:
  global-network:
    external: true
  ai_network:
    driver: bridge
    internal: true

volumes:
  ollama_data:
  pg_data:

# --- AI Services ---
services:
  ai_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_gateway_service
    restart: always
    networks:
      - global-network
      - ai_network
    ports:
      - "8090:8090"
    depends_on:
      - ollama